server/config/routes.rb
Rails.application.routes.draw do
	# Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

	# Defines the root path route ("/")
	# root "articles#index"

	# root "home#index"

	resources :url

	# get "/url", to: "url#new"
	# get "/url/:id", to: "url#show"
	delete "/url/:id", action: :destroy, to: "url#destroy"
	get '/*shorten_url', to: 'url#dynamic_redirect'
end

server/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

server/app/models/url.rb
require 'ipaddr'
require 'base64'
require 'time'
require 'securerandom'
require 'net/http'

class Url < ApplicationRecord
    @base_url = "yesyeil.ca/"
    @http_prefix = "https://"

    validates :origin_url, presence: true, uniqueness: true
    validates :shorten_url, uniqueness: true
    # validates :ipv4_address, presence: true       # This validation should be applied later for security reason (to prevent DDOS attack)

    def self.generate_shorten_url(origin_url, ipv4_address)
        url = Url.new

        # Add "https://" to the origin_url if it doesn't have it
        unless /\/\//.match(origin_url)
            origin_url = @http_prefix + origin_url
        end

        url.origin_url = origin_url
        uri = URI(url.origin_url)
        begin
            http_status = Net::HTTP.get_response(uri).code.to_i
        # Handle TCP connection error
        rescue SocketError
            return nil
        end
        
        # Generate shorten_url only if the origin_url is valid (status code: 200~399)
        if http_status < 200 && http_status >= 400
            nil
        end
        
        # Generate shorten_url with length of n (default: 1), and check if it already exists in the database
        # If it exists, increment n by 1 and generate new shorten_url
        n = 1
        new_shorten_url = @base_url + SecureRandom.urlsafe_base64(n)
        while Url.exists?(shorten_url: new_shorten_url)
            # Check if the shorten_url is already in the database for 10 times
            for i in 0..10
                new_shorten_url = @base_url + SecureRandom.urlsafe_base64(n)
                Url.exists?(shorten_url: new_shorten_url) ? next : break
            end
            n += 1
        end
        url.shorten_url = new_shorten_url

        url.time = Time.now
        url
    end

    def self.delete_shorten_url(origin_url)
        url = Url.find_by(origin_url: origin_url)
        url.destroy!
    end
end

server/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    skip_before_action :verify_authenticity_token
end

server/app/controllers/url_controller.rb
class UrlController < ApplicationController
    def new
        @url = Url.new
    end

    def create
        # Add "https://" to the origin_url if it doesn't have it
        unless /\/\//.match(url_params[:origin_url])
            origin_url = "https://" + url_params[:origin_url]
        end
        
        @url = Url.find_by(origin_url: origin_url)
        if @url
            render json: @url                       # return existing shorten_url if the origin_url already exists
            return
        end
        
        @new_url = Url.generate_shorten_url(url_params[:origin_url], request.remote_ip)
        if @new_url && @new_url.save
            render json: @new_url                   # return the shorten_url if successful
        else
            render json: { message: "Url creation was not successful." }, status: 400
        end
    end

    def index
        @urls = Url.all
        render json: @urls
    end

    def show
        @url = Url.find(params[:id])
        render json: @url
    end

    def destroy
        @url = Url.find(params[:id])
        origin_url = @url.origin_url
        @url.destroy!
        flash[:notice] = "Shorten URL of " + origin_url + " was successfully destroyed."
        redirect_to action: 'new', notice: flash[:notice]
    end

    def dynamic_redirect
        base_url = "url.yesyeil.ca/"
        @url = Url.find_by(shorten_url: base_url+params[:shorten_url])
        if @url
            redirect_to @url.origin_url, allow_other_host: true
        else
            render json: { error: "Url not found" }, status: 404
        end
    end

    private

    def url_params
        params.require(:url).permit(:origin_url)
    end
end

server/app/helpers/application_helper.rb
module ApplicationHelper
end

server/app/helpers/url_helper.rb
module UrlHelper
end

server/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Server</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

server/app/views/url/index.html.erb
# code will be updated for the admin account

# <!-- app/views/url/index.html.erb -->
<% if flash[:notice] %>
  <div class="notice"><%= flash[:notice] %></div>
<% end %>

<p>
    <strong>Origin url:</strong> <%= @url.origin_url %>
</p>

<p>
    <strong>Shorten url:</strong> <%= @url.shorten_url %>
</p>

<%= link_to 'Delete', url_path(@url), method: :delete, data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  }%>

<%= link_to 'Back', new_url_path %>

server/app/views/url/new.html.erb
<% if flash[:notice] %>
  <div class="notice"><%= flash[:notice] %></div>
<% end %>

<%= form_for :url, url:url_index_path do |f| %>
    <p>
        <%= f.label :origin_url %><br>
        <%= f.text_field :origin_url %>
    </p>
    
    <p>
        <%= f.submit %>
    </p>
<% end %>